//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CladSmartTest.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public long nik { get; set; }
        public string name { get; set; }
        public long department_id { get; set; }
        public string position { get; set; }
        public Nullable<bool> bpjs_allowance { get; set; }
        public Nullable<bool> meal_allowance { get; set; }
        public Nullable<bool> laptop_allowance { get; set; }
    
        public virtual department department { get; set; }
    }
}
